// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1bTtUdZMgY_FGxdJ1d1BtRGzWVK0o2A',
    appId: '1:524885612145:web:c4270e23ce76841063add0',
    messagingSenderId: '524885612145',
    projectId: 'weniai',
    authDomain: 'weniai.firebaseapp.com',
    storageBucket: 'weniai.firebasestorage.app',
    measurementId: 'G-GD938P2985',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWOx2m3UP7aD3gjrd_aXXUOp0McmfOB8',
    appId: '1:524885612145:android:90de0c9a4820a0a163add0',
    messagingSenderId: '524885612145',
    projectId: 'weniai',
    storageBucket: 'weniai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWQf4b5CioeUSFRCcsSi3qUsd87kH_iE',
    appId: '1:524885612145:ios:65c129e3d5d03bb863add0',
    messagingSenderId: '524885612145',
    projectId: 'weniai',
    storageBucket: 'weniai.firebasestorage.app',
    iosBundleId: 'com.example.weniAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbWQf4b5CioeUSFRCcsSi3qUsd87kH_iE',
    appId: '1:524885612145:ios:65c129e3d5d03bb863add0',
    messagingSenderId: '524885612145',
    projectId: 'weniai',
    storageBucket: 'weniai.firebasestorage.app',
    iosBundleId: 'com.example.weniAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG1bTtUdZMgY_FGxdJ1d1BtRGzWVK0o2A',
    appId: '1:524885612145:web:7e50641fdaa587ab63add0',
    messagingSenderId: '524885612145',
    projectId: 'weniai',
    authDomain: 'weniai.firebaseapp.com',
    storageBucket: 'weniai.firebasestorage.app',
    measurementId: 'G-FFFZ6WKEM1',
  );
}
